schema = 1
compiler = "0.11.1"

[[modules]]
name = "Fmt"
python = "gandora_tool/fmt.py"
source = "gandora_tool/_gan/gandora_tool/fmt.gan"

[[modules]]
name = "Main"
python = "gandora_tool/main.py"
source = "gandora_tool/_gan/gandora_tool/main.gan"
