schema = 1
compiler = "0.10.2"

[[modules]]
name = "Lsc"
python = "gandora_lsp/lsc.py"
source = "gandora_lsp/_gan/gandora_lsp/lsc.gan"

[[modules]]
name = "Main"
python = "gandora_lsp/main.py"
source = "gandora_lsp/_gan/gandora_lsp/main.gan"

[[modules]]
name = "PyIntel"
python = "gandora_lsp/py_intel.py"
source = "gandora_lsp/_gan/gandora_lsp/py_intel.gan"
