use gandora_core::{codegen, diag, expander, parser, printer, project};

use std::path::{Path, PathBuf};
use std::process::ExitCode;

use diag::{Diagnostic, Span};

const USAGE: &str = "\
ganc - the Gandora stage-0 compiler (GEP-0013; `gan` is the task runner)

Usage:
  ganc init [--existing] [path]   create a new Gandora + uv project
  ganc check [file...]            parse, expand, and analyze without output
  ganc build                      compile the project into outDir
  ganc compile <file...> [--out <dir>]
  ganc run <file> [args...]       compile and execute with the project Python
  ganc expand <file>              print a module after macro expansion
  ganc doc <Mod>[.<fun>] [--locale <tag>]   print documentation
  ganc test                       run doctests of every compiled module
  ganc --version                  print the compiler version
";

fn main() -> ExitCode {
    let args: Vec<String> = std::env::args().skip(1).collect();
    let cmd = match args.first().map(String::as_str) {
        Some("--version") | Some("-V") => {
            println!("ganc {}", env!("CARGO_PKG_VERSION"));
            return ExitCode::SUCCESS;
        }
        Some("--help") | Some("-h") | None => {
            print!("{USAGE}");
            return if args.is_empty() {
                ExitCode::from(2)
            } else {
                ExitCode::SUCCESS
            };
        }
        Some(c) => c.to_string(),
    };
    let rest = &args[1..];
    let result = match cmd.as_str() {
        "init" => cmd_init(rest),
        "check" => cmd_check(rest),
        "build" => cmd_build(),
        "compile" => cmd_compile(rest),
        "run" => return cmd_run(rest),
        "expand" => cmd_expand(rest),
        "doc" => cmd_doc(rest),
        "test" => return cmd_test(),
        other => {
            eprintln!("ganc: unknown command '{other}'\n\n{USAGE}");
            return ExitCode::from(2);
        }
    };
    match result {
        Ok(()) => ExitCode::SUCCESS,
        Err(e) => {
            eprintln!("{e}");
            ExitCode::FAILURE
        }
    }
}

fn usage_err(msg: &str) -> Diagnostic {
    Diagnostic::new("gan", Span::default(), format!("{msg}\n\n{USAGE}"))
}

// ---- init ----------------------------------------------------------------

const INIT_MAIN: &str = r#"defmodule Main do
  @moduledoc "Entry point generated by gan init."

  def main() do
    IO.puts("Hello from Gandora!")
    IO.puts("2 + 2 * 2 = #{2 + 2 * 2}")
    IO.puts("$math.sqrt(2.0) = #{$math.sqrt(2.0)}")
  end
end
"#;

const INIT_CONFIG: &str = r#"{
  // Gandora compiler configuration (GEP-0001).
  // Python package metadata and dependencies stay in pyproject.toml.
  "source": ["src"],
  "outDir": "dist",
  "targetPython": "3.11"
}
"#;

const INIT_GITIGNORE: &str =
    "__pycache__/\n*.py[oc]\ndist/\n.gandora/\n.venv/\ngandora.local.jsonc\n";

fn cmd_init(args: &[String]) -> Result<(), Diagnostic> {
    if args.iter().any(|a| a == "--package") {
        return cmd_init_package(args);
    }
    let existing = args.iter().any(|a| a == "--existing");
    let path: PathBuf = args
        .iter()
        .find(|a| !a.starts_with("--"))
        .map(PathBuf::from)
        .unwrap_or_else(|| PathBuf::from("."));
    if !existing {
        if path.exists() && path != Path::new(".") {
            return Err(Diagnostic::new(
                path.display().to_string(),
                Span::default(),
                "path already exists; use `gan init --existing` to join it",
            ));
        }
        std::fs::create_dir_all(&path).map_err(io_err(&path))?;
    } else if !path.exists() {
        return Err(Diagnostic::new(
            path.display().to_string(),
            Span::default(),
            "--existing requires an existing directory",
        ));
    }
    let name = path
        .canonicalize()
        .ok()
        .and_then(|p| p.file_name().map(|n| n.to_string_lossy().to_string()))
        .unwrap_or_else(|| "gandora-app".to_string());

    write_if_absent(&path.join("gandora.jsonc"), INIT_CONFIG)?;
    write_if_absent(&path.join(".gitignore"), INIT_GITIGNORE)?;
    write_if_absent(&path.join(".python-version"), "3.11\n")?;
    // the stdlib ships on PyPI in lockstep with the compiler (GEP-0010-R001)
    let pyproject = format!(
        "[project]\nname = \"{name}\"\nversion = \"0.1.0\"\ndescription = \"A Gandora project\"\nrequires-python = \">=3.11\"\ndependencies = [\"gandora-std>={v}\"]\n\n[dependency-groups]\ndev = [\"gandora-tool[dev]>={v}\"]\n",
        v = env!("CARGO_PKG_VERSION")
    );
    write_if_absent(&path.join("pyproject.toml"), &pyproject)?;
    std::fs::create_dir_all(path.join("src")).map_err(io_err(&path))?;
    write_if_absent(&path.join("src/main.gan"), INIT_MAIN)?;
    println!("Initialized Gandora project in {}", path.display());
    println!("Next steps:");
    if path != Path::new(".") {
        println!("  cd {}", path.display());
    }
    println!("  gan run src/main.gan");
    Ok(())
}

/// `gan init --package <name>`: a publishable package project (GEP-0006-R001).
fn cmd_init_package(args: &[String]) -> Result<(), Diagnostic> {
    let path: PathBuf = args
        .iter()
        .find(|a| !a.starts_with("--"))
        .map(PathBuf::from)
        .ok_or_else(|| usage_err("init --package requires a package name"))?;
    if path.exists() {
        return Err(Diagnostic::new(
            path.display().to_string(),
            Span::default(),
            "path already exists",
        ));
    }
    let dist_name = path
        .file_name()
        .map(|n| n.to_string_lossy().to_string())
        .unwrap_or_else(|| "gandora-pkg".to_string());
    let py_pkg = dist_name.replace('-', "_");
    let module = project::snake_to_camel(&py_pkg);
    std::fs::create_dir_all(path.join("src").join(&py_pkg)).map_err(io_err(&path))?;

    // outDir must not be `dist`: hatchling excludes its own artifact
    // directory from wheel inputs
    let config = r#"{
  // Gandora package project (GEP-0006): `gan build` also emits the
  // gandora.toml marker and ships .gan sources for macro consumers.
  "source": ["src"],
  "outDir": "pkg",
  "targetPython": "3.11",
  "package": true
}
"#;
    std::fs::write(path.join("gandora.jsonc"), config).map_err(io_err(&path))?;
    let pyproject = format!(
        r#"[project]
name = "{dist_name}"
version = "0.1.0"
description = "A Gandora package"
requires-python = ">=3.11"
dependencies = []

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

# pkg/ is gitignored build output but must enter the distribution
[tool.hatch.build]
ignore-vcs = true

# the sdist carries sources and the compiled output of `gan build`
[tool.hatch.build.targets.sdist]
include = ["pkg", "src", "gandora.jsonc"]

# the wheel packages the compiled output (marker and .gan sources included)
[tool.hatch.build.targets.wheel]
packages = ["pkg/{py_pkg}"]
"#
    );
    std::fs::write(path.join("pyproject.toml"), pyproject).map_err(io_err(&path))?;
    std::fs::write(
        path.join(".gitignore"),
        format!("{INIT_GITIGNORE}pkg/\n"),
    )
    .map_err(io_err(&path))?;
    std::fs::write(path.join(".python-version"), "3.11\n").map_err(io_err(&path))?;
    let starter = format!(
        r#"defmodule {module}.Core do
  @moduledoc "Public surface of {dist_name}: functions run anywhere, macros expand in consumers."

  def hello(name), do: "Hello from {dist_name}, #{{name}}!"

  defmacro twice(expr) do
    quote do
      {{unquote(expr), unquote(expr)}}
    end
  end
end
"#
    );
    std::fs::write(path.join("src").join(&py_pkg).join("core.gan"), starter)
        .map_err(io_err(&path))?;
    println!("Initialized Gandora package {dist_name} in {}", path.display());
    println!("Publish with:");
    println!("  cd {}", path.display());
    println!("  gan build && uv build && uv publish");
    Ok(())
}

fn write_if_absent(path: &Path, content: &str) -> Result<(), Diagnostic> {
    if path.exists() {
        return Ok(());
    }
    std::fs::write(path, content).map_err(io_err(path))
}

fn io_err(path: &Path) -> impl Fn(std::io::Error) -> Diagnostic + '_ {
    move |e| Diagnostic::new(path.display().to_string(), Span::default(), e.to_string())
}

// ---- project helpers -----------------------------------------------------

fn config_for_cwd() -> Result<project::Config, Diagnostic> {
    let cwd = std::env::current_dir()
        .map_err(|e| Diagnostic::new("gan", Span::default(), e.to_string()))?;
    match project::find_config(&cwd)? {
        Some(c) => Ok(c),
        None => Ok(project::Config::default_at(cwd)),
    }
}

fn config_for_file(file: &Path) -> Result<project::Config, Diagnostic> {
    let dir = file
        .canonicalize()
        .map_err(io_err(file))?
        .parent()
        .map(|p| p.to_path_buf())
        .unwrap_or_default();
    match project::find_config(&dir)? {
        Some(c) => Ok(c),
        None => Ok(project::Config::default_at(dir)),
    }
}

fn sources_or_explicit(
    config: &project::Config,
    files: &[String],
) -> Result<Vec<(PathBuf, Vec<String>)>, Diagnostic> {
    if files.is_empty() {
        let sources = project::discover_sources(config)?;
        project::check_collisions(&sources)?;
        return Ok(sources);
    }
    let mut out = Vec::new();
    for f in files {
        let path = PathBuf::from(f).canonicalize().map_err(io_err(Path::new(f)))?;
        let module = module_for(config, &path)?;
        out.push((path, module));
    }
    Ok(out)
}

fn module_for(config: &project::Config, path: &Path) -> Result<Vec<String>, Diagnostic> {
    for root in &config.source {
        let root_path = config.root.join(root);
        if let Ok(canon_root) = root_path.canonicalize() {
            if path.starts_with(&canon_root) {
                return project::module_name_for(path, &canon_root);
            }
        }
    }
    // outside a source root: derive from the file name only
    project::module_name_for(path, path.parent().unwrap_or(Path::new("")))
}

/// The whole project compiled together with `file` guaranteed included.
fn compile_project_with(
    config: &project::Config,
    file: &Path,
) -> Result<Vec<project::CompiledModule>, Diagnostic> {
    let mut sources = project::discover_sources(config)?;
    let canon = file.canonicalize().map_err(io_err(file))?;
    if !sources.iter().any(|(p, _)| *p == canon) {
        let module = module_for(config, &canon)?;
        sources.push((canon, module));
    }
    project::check_collisions(&sources)?;
    project::compile_files(&sources, Some(&config))
}

// ---- commands ------------------------------------------------------------

fn cmd_check(args: &[String]) -> Result<(), Diagnostic> {
    let config = config_for_cwd()?;
    let sources = sources_or_explicit(&config, args)?;
    if sources.is_empty() {
        println!("no .gan sources found");
        return Ok(());
    }
    let modules = project::compile_files(&sources, Some(&config))?;
    for m in &modules {
        for w in &m.warnings {
            eprintln!("warning: {}:{}: {}", w.file, w.span.line, w.message);
        }
    }
    println!("checked {} module(s), no errors", modules.len());
    Ok(())
}

fn cmd_build() -> Result<(), Diagnostic> {
    let config = config_for_cwd()?;
    let modules = project::compile_project(&config)?;
    if modules.is_empty() {
        println!("no .gan sources found");
        return Ok(());
    }
    for m in &modules {
        for w in &m.warnings {
            eprintln!("warning: {}:{}: {}", w.file, w.span.line, w.message);
        }
    }
    let out_root = config.root.join(&config.out_dir);
    project::write_outputs(&modules, &out_root)?;
    if config.package {
        let tops = project::write_package_artifacts(&modules, &out_root)?;
        for top in tops {
            println!("packaged {top} (marker + shipped sources)");
        }
    }
    let macro_only = modules.iter().filter(|m| m.compile_time_only).count();
    if macro_only > 0 {
        println!(
            "compiled {} module(s) into {} ({macro_only} macro-only, no runtime output)",
            modules.len() - macro_only,
            out_root.display()
        );
    } else {
        println!(
            "compiled {} module(s) into {}",
            modules.len(),
            out_root.display()
        );
    }
    Ok(())
}

fn cmd_compile(args: &[String]) -> Result<(), Diagnostic> {
    let mut files = Vec::new();
    let mut out_dir: Option<String> = None;
    let mut it = args.iter();
    while let Some(a) = it.next() {
        if a == "--out" {
            out_dir = it.next().cloned();
            if out_dir.is_none() {
                return Err(usage_err("--out requires a directory"));
            }
        } else {
            files.push(a.clone());
        }
    }
    if files.is_empty() {
        return Err(usage_err("compile requires at least one file"));
    }
    let config = config_for_file(Path::new(&files[0]))?;
    let sources = sources_or_explicit(&config, &files)?;
    let modules = project::compile_files(&sources, Some(&config))?;
    let out_root = match out_dir {
        Some(d) => PathBuf::from(d),
        None => config.root.join(&config.out_dir),
    };
    let written = project::write_outputs(&modules, &out_root)?;
    for w in written {
        println!("{}", w.display());
    }
    Ok(())
}

fn cmd_expand(args: &[String]) -> Result<(), Diagnostic> {
    let file = args
        .first()
        .ok_or_else(|| usage_err("expand requires a file"))?;
    let path = Path::new(file);
    let config = config_for_file(path)?;
    let canon = path.canonicalize().map_err(io_err(path))?;
    // macros from the whole project are visible, as during compilation
    let mut sources = project::discover_sources(&config)?;
    if !sources.iter().any(|(p, _)| *p == canon) {
        let module = module_for(&config, &canon)?;
        sources.push((canon.clone(), module));
    }
    let mut table = expander::MacroTable::new();
    let mut target = None;
    for (source, _) in &sources {
        let name = source.display().to_string();
        let text = std::fs::read_to_string(source).map_err(io_err(source))?;
        let term = parser::parse_file(&name, &text)?;
        for (k, v) in expander::collect_macros(&name, &term)? {
            table.entry(k).or_insert(v);
        }
        if *source == canon {
            target = Some(term);
        }
    }
    let term = target.ok_or_else(|| usage_err("expand requires a file"))?;
    let mut ex = expander::Expander::new(file, table);
    let expanded = ex.expand_module(&term)?;
    print!("{}", printer::print_module(&expanded));
    Ok(())
}

fn cmd_run(args: &[String]) -> ExitCode {
    let Some(file) = args.first() else {
        eprintln!("{}", usage_err("run requires a file"));
        return ExitCode::from(2);
    };
    let file_path = PathBuf::from(file);
    let config = match config_for_file(&file_path) {
        Ok(c) => c,
        Err(e) => {
            eprintln!("{e}");
            return ExitCode::FAILURE;
        }
    };
    let modules = match compile_project_with(&config, &file_path) {
        Ok(m) => m,
        Err(e) => {
            eprintln!("{e}");
            return ExitCode::FAILURE;
        }
    };
    let cache_root = config.root.join(".gandora/cache");
    if let Err(e) = project::write_outputs(&modules, &cache_root) {
        eprintln!("{e}");
        return ExitCode::FAILURE;
    }
    let canon = match file_path.canonicalize() {
        Ok(c) => c,
        Err(e) => {
            eprintln!("ganc: {e}");
            return ExitCode::FAILURE;
        }
    };
    let Some(target) = modules.iter().find(|m| m.source == canon) else {
        eprintln!("ganc: internal error: target module missing from build");
        return ExitCode::FAILURE;
    };
    if target.compile_time_only {
        eprintln!(
            "ganc: {} defines only macros; there is nothing to run (GEP-0002-R009)",
            target.module.join(".")
        );
        return ExitCode::FAILURE;
    }
    let script = cache_root.join(&target.py_path);
    let (program, mut pre_args) = project::interpreter_command(&config.root);
    // -P (PYTHONSAFEPATH) keeps the script's own directory off sys.path, so
    // a generated module like tour/numpy.py cannot shadow the real numpy
    // for its siblings; project modules resolve through PYTHONPATH instead.
    pre_args.push("-P".to_string());
    pre_args.push(script.display().to_string());
    pre_args.extend(args[1..].iter().cloned());
    let mut command = std::process::Command::new(&program);
    command.args(&pre_args);
    let existing = std::env::var("PYTHONPATH").unwrap_or_default();
    let pythonpath = if existing.is_empty() {
        cache_root.display().to_string()
    } else {
        format!("{}:{existing}", cache_root.display())
    };
    command.env("PYTHONPATH", pythonpath);
    match command.status() {
        Ok(status) => match status.code() {
            Some(code) => ExitCode::from(code.clamp(0, 255) as u8),
            None => ExitCode::FAILURE,
        },
        Err(e) => {
            eprintln!("ganc: failed to launch {program}: {e}");
            ExitCode::FAILURE
        }
    }
}

// ---- documentation (GEP-0007) --------------------------------------------

/// RFC 4647-style lookup over doc entries (GEP-0007-R004).
fn lookup_locale<'a>(info: &'a codegen::DocInfo, locale: Option<&str>) -> Option<&'a str> {
    if let Some(tag) = locale {
        let want = tag.to_lowercase();
        // exact, then an entry the request is a prefix of, then shorten
        if let Some((_, text)) = info
            .entries
            .iter()
            .find(|(t, _)| t.to_lowercase() == want)
        {
            return Some(text);
        }
        if let Some((_, text)) = info
            .entries
            .iter()
            .find(|(t, _)| t.to_lowercase().starts_with(&format!("{want}-")))
        {
            return Some(text);
        }
        if let Some((head, _)) = want.rsplit_once('-') {
            return lookup_locale(info, Some(head));
        }
    }
    info.default_text()
}

fn cmd_doc(args: &[String]) -> Result<(), Diagnostic> {
    let mut target: Option<String> = None;
    let mut locale: Option<String> = None;
    let mut it = args.iter();
    while let Some(a) = it.next() {
        if a == "--locale" {
            locale = it.next().cloned();
            if locale.is_none() {
                return Err(usage_err("--locale requires a BCP 47 tag"));
            }
        } else {
            target = Some(a.clone());
        }
    }
    let Some(target) = target else {
        return Err(usage_err("doc requires a Module or Module.function target"));
    };
    // developer preference when no --locale: project-local file first,
    // then the environment (GEP-0015-R015)
    if locale.is_none() {
        locale = config_for_cwd()
            .ok()
            .and_then(|c| project::local_pref(&c.root, "docLocale"))
            .or_else(|| std::env::var("GAN_DOC_LOCALE").ok())
            .filter(|l| !l.is_empty() && l != "all");
    }
    // `App.Mod.fun` -> module App.Mod + function fun; `App.Mod` -> module doc
    let segs: Vec<&str> = target.split('.').collect();
    let (module_name, fun) = match segs.last() {
        Some(last) if last.chars().next().is_some_and(|c| c.is_lowercase()) => {
            (segs[..segs.len() - 1].join("."), Some((*last).to_string()))
        }
        _ => (target.clone(), None),
    };
    // compiler built-ins (IO, Kernel-style functions) carry embedded docs
    if let Some(info) = builtin_doc(&target) {
        print_doc(&target, Some(info), locale.as_deref());
        return Ok(());
    }
    if module_name.is_empty() {
        return Err(usage_err(
            "doc target must include a module name (or name a built-in like `gan doc length`)",
        ));
    }
    let config = config_for_cwd()?;
    // locate the module source: project first, then installed packages
    let mut source: Option<PathBuf> = None;
    for (path, module) in project::discover_sources(&config)? {
        if module.join(".") == module_name {
            source = Some(path);
            break;
        }
    }
    if source.is_none() {
        source = project::find_installed_source(&config, &module_name);
    }
    let Some(_source) = source else {
        return Err(Diagnostic::new(
            "gan",
            Span::default(),
            format!("module {module_name} not found in project sources or installed packages"),
        ));
    };
    // the walk itself lives in project::find_doc — one implementation
    // shared with the LSP/lsc (specs, params, recursion shape, the lot)
    let info = project::find_doc(&config, &module_name, fun.as_deref())?;
    let label = match &fun {
        Some(f) => format!("{module_name}.{f}"),
        None => module_name.clone(),
    };
    print_doc(&label, info, locale.as_deref());
    Ok(())
}

fn print_doc(label: &str, info: Option<codegen::DocInfo>, locale: Option<&str>) {
    match info {
        Some(info) if info.hidden => println!("{label} is hidden (@doc false)"),
        Some(info) => {
            for spec in &info.specs {
                println!("{spec}");
            }
            if let Some(shape) = info.tco.as_deref() {
                let zh = locale.is_some_and(|l| l.starts_with("zh"));
                println!(
                    "{}",
                    match (shape, zh) {
                        ("loop", false) => {
                            "recursion: compiles to a while loop (tail call \
                             optimized, constant stack)"
                        }
                        ("loop", true) => "递归:编译为 while 循环(尾调用已优化,常数栈)",
                        (_, false) => {
                            "recursion: compiles to native recursion (not in tail \
                             position, uses the call stack)"
                        }
                        (_, true) => "递归:编译为原生递归(非尾位置,使用调用栈)",
                    }
                );
            }
            let prose = lookup_locale(&info, locale);
            let heading = match locale {
                Some(l) if l.starts_with("zh") => "## 参数",
                _ => "## Parameters",
            };
            let params = codegen::params_section(
                &info,
                locale.unwrap_or("default"),
                heading,
            );
            if prose.is_none() && info.meta.is_empty() && info.examples.is_empty() {
                println!("{label} has no documentation");
            } else {
                // metadata first: deprecation is the thing to see immediately
                if let Some(v) = info.meta_value("deprecated") {
                    println!("[deprecated] {v}");
                }
                for (k, v) in &info.meta {
                    if k != "deprecated" {
                        println!("{k}: {v}");
                    }
                }
                if !info.meta.is_empty() {
                    println!();
                }
                if let Some(text) = prose {
                    print!(
                        "{}",
                        ensure_trailing_newline(text.trim_start_matches('\n').trim_end())
                    );
                }
                if let Some(section) = &params {
                    println!();
                    print!("{}", ensure_trailing_newline(section));
                }
                // example blocks render in every locale (GEP-0007-R009)
                for ex in &info.examples {
                    println!();
                    print!("{}", ensure_trailing_newline(ex.trim_end()));
                }
            }
        }
        None => println!("{label} has no documentation"),
    }
}

/// Embedded bilingual docs for compiler built-ins (GEP-0007): the IO
/// pseudo-module and the Kernel-style functions of GEP-0001-R006.
fn builtin_doc(target: &str) -> Option<codegen::DocInfo> {
    let make = |en: &str, zh: &str, example: Option<&str>| {
        let mut info = codegen::DocInfo::default();
        info.entries.push(("default".into(), en.to_string()));
        info.entries.push(("zh-CN".into(), zh.to_string()));
        if let Some(ex) = example {
            info.examples.push(ex.to_string());
        }
        info
    };
    Some(match target {
        "IO" => make(
            "Built-in console I/O. `IO.puts/1` compiles to `print(...)`; \
             `IO.inspect/1` prints the repr and returns the value.",
            "内建控制台 I/O。`IO.puts/1` 编译为 `print(...)`；`IO.inspect/1` \
             打印 repr 并返回原值。",
            None,
        ),
        "IO.puts" => make(
            "Writes a line to stdout. Compiles to Python `print(value)` — \
             no wrapper, no runtime.",
            "向标准输出写一行。编译为 Python 的 `print(value)`——无包装、无运行时。",
            Some("    gan> IO.puts(\"hello\")\n    hello"),
        ),
        "IO.inspect" => make(
            "Prints the `repr` of a value and returns the value, for \
             pipeline-friendly debugging. Compiles to an inlined helper.",
            "打印值的 `repr` 并返回原值，便于管道调试。编译为内联辅助函数。",
            None,
        ),
        "length" => make(
            "The number of elements in a list. Compiles to Python `len(list)`.",
            "列表的元素个数。编译为 Python 的 `len(list)`。",
            Some("    gan> length([1, 2, 3])\n    3"),
        ),
        "hd" => make(
            "The head of a non-empty list; compiles to `list[0]`.",
            "非空列表的头部；编译为 `list[0]`。",
            None,
        ),
        "tl" => make(
            "The tail of a non-empty list; compiles to `list[1:]`.",
            "非空列表的尾部；编译为 `list[1:]`。",
            None,
        ),
        "elem" => make(
            "`elem(tuple, i)` reads a tuple element; compiles to `tuple[i]`.",
            "`elem(tuple, i)` 读取元组元素；编译为 `tuple[i]`。",
            None,
        ),
        "inspect" => make(
            "The `repr` of a value as a string — what doctest expected \
             output shows (GEP-0007-R008).",
            "值的 `repr` 字符串——即 doctest 期望输出所展示的内容（GEP-0007-R008）。",
            Some("    gan> inspect({:ok, 1})\n    \"('ok', 1)\""),
        ),
        "to_string" => make(
            "Converts a value to a string; compiles to Python `str(value)`.",
            "将值转换为字符串；编译为 Python 的 `str(value)`。",
            None,
        ),
        "div" => make(
            "Integer division truncated toward zero (Elixir semantics), \
             unlike Python's floor `//`.",
            "向零截断的整数除法（Elixir 语义），不同于 Python 向下取整的 `//`。",
            Some("    gan> div(-7, 2)\n    -3"),
        ),
        "rem" => make(
            "Remainder of truncated division (Elixir semantics): the sign \
             follows the dividend, unlike Python's `%`.",
            "截断除法的余数（Elixir 语义）：符号跟随被除数，不同于 Python 的 `%`。",
            Some("    gan> rem(-7, 2)\n    -1"),
        ),
        "raise" => make(
            "Raises a `RuntimeError` with the given message.",
            "抛出携带给定消息的 `RuntimeError`。",
            None,
        ),
        "map_size" | "tuple_size" => make(
            "The number of entries; compiles to Python `len(value)`.",
            "条目数量；编译为 Python 的 `len(value)`。",
            None,
        ),
        "abs" | "max" | "min" | "round" => make(
            "Compiles directly to the Python builtin of the same name.",
            "直接编译为同名的 Python 内建函数。",
            None,
        ),
        "trunc" => make(
            "Truncates a number to an integer; compiles to `int(value)`.",
            "将数字截断为整数；编译为 `int(value)`。",
            None,
        ),
        t if t.starts_with("is_")
            && matches!(
                t,
                "is_nil" | "is_list" | "is_tuple" | "is_map" | "is_binary" | "is_atom"
                    | "is_integer" | "is_float" | "is_function" | "is_boolean"
            ) =>
        {
            make(
                "Type predicate over the GEP-0001-R009 data mapping; compiles \
                 to an `isinstance` (or `is None` / `callable`) check.",
                "基于 GEP-0001-R009 数据映射的类型判断；编译为 `isinstance`\
                 （或 `is None` / `callable`）检查。",
                None,
            )
        }
        _ => return None,
    })
}

fn ensure_trailing_newline(s: &str) -> String {
    if s.ends_with('\n') {
        s.to_string()
    } else {
        format!("{s}\n")
    }
}

/// Run every generated module through Python's doctest runner (GEP-0007-R008).
fn cmd_test() -> ExitCode {
    let config = match config_for_cwd() {
        Ok(c) => c,
        Err(e) => {
            eprintln!("{e}");
            return ExitCode::FAILURE;
        }
    };
    let modules = match project::compile_project(&config) {
        Ok(m) => m,
        Err(e) => {
            eprintln!("{e}");
            return ExitCode::FAILURE;
        }
    };
    let cache_root = config.root.join(".gandora/cache");
    if let Err(e) = project::write_outputs(&modules, &cache_root) {
        eprintln!("{e}");
        return ExitCode::FAILURE;
    }
    let (program, base_args) = project::interpreter_command(&config.root);
    let mut checked = 0usize;
    let mut failed = 0usize;
    // import by dotted module name (not file path): `python -m doctest file`
    // inserts the file's own directory into sys.path, which lets a module
    // like tour/numpy.py shadow the real numpy for its siblings
    const RUNNER: &str = "import sys, doctest, importlib\n\
                          mod = importlib.import_module(sys.argv[1])\n\
                          sys.exit(1 if doctest.testmod(mod).failed else 0)";
    for m in modules.iter().filter(|m| !m.compile_time_only) {
        let dotted = m.py_path.trim_end_matches(".py").replace('/', ".");
        let mut command = std::process::Command::new(&program);
        command.args(&base_args);
        command.args(["-P", "-c", RUNNER, &dotted]);
        command.env("PYTHONPATH", &cache_root);
        checked += 1;
        match command.status() {
            Ok(status) if status.success() => {}
            Ok(_) => {
                eprintln!("doctest failures in {}", m.module.join("."));
                failed += 1;
            }
            Err(e) => {
                eprintln!("ganc: failed to launch {program}: {e}");
                return ExitCode::FAILURE;
            }
        }
    }
    println!("doctests: {checked} module(s) checked, {failed} failed");
    // the tests/ directory: test_*.gan compiled with the whole project
    // context, executed by pytest (GEP-0024)
    let tests_failed = match run_test_files(&config, &program, &base_args, &cache_root) {
        Ok(f) => f,
        Err(e) => {
            eprintln!("{e}");
            return ExitCode::FAILURE;
        }
    };
    if failed == 0 && !tests_failed {
        ExitCode::SUCCESS
    } else {
        ExitCode::FAILURE
    }
}

/// Compile `tests/*.gan` together with the project sources and run
/// pytest over the compiled tree (GEP-0024). Returns whether anything
/// failed; quietly does nothing when there is no tests directory.
fn run_test_files(
    config: &project::Config,
    program: &str,
    base_args: &[String],
    cache_root: &Path,
) -> Result<bool, Diagnostic> {
    let tests_dir = config.root.join("tests");
    if !tests_dir.is_dir() {
        return Ok(false);
    }
    let mut test_files: Vec<PathBuf> = std::fs::read_dir(&tests_dir)
        .map_err(io_err(&tests_dir))?
        .filter_map(|e| e.ok().map(|e| e.path()))
        .filter(|p| p.extension().is_some_and(|x| x == "gan"))
        .collect();
    test_files.sort();
    if test_files.is_empty() {
        return Ok(false);
    }
    let mut sources = project::discover_sources(config)?;
    for f in &test_files {
        let module = project::module_name_for(f, &tests_dir)?;
        sources.push((f.clone(), module));
    }
    let modules = project::compile_files(&sources, Some(config))?;
    let out_root = config.root.join(".gandora/tests");
    // only the test modules live here; project modules import from the
    // doctest cache via PYTHONPATH
    let test_names: std::collections::BTreeSet<String> = test_files
        .iter()
        .filter_map(|f| f.file_stem().map(|s| s.to_string_lossy().to_string()))
        .collect();
    let test_modules: Vec<project::CompiledModule> = modules
        .into_iter()
        .filter(|m| {
            m.py_path
                .rsplit('/')
                .next()
                .map(|f| test_names.contains(f.trim_end_matches(".py")))
                .unwrap_or(false)
        })
        .collect();
    project::write_outputs(&test_modules, &out_root)?;
    let sep = if cfg!(windows) { ";" } else { ":" };
    let pythonpath = format!(
        "{}{sep}{}",
        cache_root.display(),
        std::env::var("PYTHONPATH").unwrap_or_default()
    );
    let mut command = std::process::Command::new(program);
    command.args(base_args);
    command.args(["-m", "pytest", &out_root.display().to_string(), "-q"]);
    command.env("PYTHONPATH", pythonpath);
    match command.status() {
        Ok(status) => Ok(!status.success()),
        Err(e) => {
            eprintln!(
                "ganc: could not run pytest ({e}); add it with `uv add --dev pytest`"
            );
            Ok(true)
        }
    }
}
