schema = 1
compiler = "0.19.0"

[[modules]]
name = "Enum"
python = "gandora_std/enum.py"
source = "gandora_std/_gan/gandora_std/enum.gan"

[[modules]]
name = "File"
python = "gandora_std/file.py"
source = "gandora_std/_gan/gandora_std/file.gan"

[[modules]]
name = "Keyword"
python = "gandora_std/keyword.py"
source = "gandora_std/_gan/gandora_std/keyword.gan"

[[modules]]
name = "List"
python = "gandora_std/list.py"
source = "gandora_std/_gan/gandora_std/list.gan"

[[modules]]
name = "Map"
python = "gandora_std/map.py"
source = "gandora_std/_gan/gandora_std/map.gan"

[[modules]]
name = "Path"
python = "gandora_std/path.py"
source = "gandora_std/_gan/gandora_std/path.gan"

[[modules]]
name = "String"
python = "gandora_std/string.py"
source = "gandora_std/_gan/gandora_std/string.gan"

[[modules]]
name = "System"
python = "gandora_std/system.py"
source = "gandora_std/_gan/gandora_std/system.gan"

[[modules]]
name = "Task"
python = "gandora_std/task.py"
source = "gandora_std/_gan/gandora_std/task.gan"

[[modules]]
name = "Test"
python = "gandora_std/test.py"
source = "gandora_std/_gan/gandora_std/test.gan"
