mod ast;
mod codegen;
mod diag;
mod expander;
mod jsonc;
mod lexer;
mod parser;
mod printer;
mod project;

use std::path::{Path, PathBuf};
use std::process::ExitCode;

use diag::{Diagnostic, Span};

const USAGE: &str = "\
gan - the Gandora compiler

Usage:
  gan init [--existing] [path]   create a new Gandora + uv project
  gan check [file...]            parse, expand, and analyze without output
  gan build                      compile the project into outDir
  gan compile <file...> [--out <dir>]
  gan run <file> [args...]       compile and execute with the project Python
  gan expand <file>              print a module after macro expansion
  gan doc <Mod>[.<fun>] [--locale <tag>]   print documentation
  gan test                       run doctests of every compiled module
  gan --version                  print the compiler version
";

fn main() -> ExitCode {
    let args: Vec<String> = std::env::args().skip(1).collect();
    let cmd = match args.first().map(String::as_str) {
        Some("--version") | Some("-V") => {
            println!("gan {}", env!("CARGO_PKG_VERSION"));
            return ExitCode::SUCCESS;
        }
        Some("--help") | Some("-h") | None => {
            print!("{USAGE}");
            return if args.is_empty() {
                ExitCode::from(2)
            } else {
                ExitCode::SUCCESS
            };
        }
        Some(c) => c.to_string(),
    };
    let rest = &args[1..];
    let result = match cmd.as_str() {
        "init" => cmd_init(rest),
        "check" => cmd_check(rest),
        "build" => cmd_build(),
        "compile" => cmd_compile(rest),
        "run" => return cmd_run(rest),
        "expand" => cmd_expand(rest),
        "doc" => cmd_doc(rest),
        "test" => return cmd_test(),
        other => {
            eprintln!("gan: unknown command '{other}'\n\n{USAGE}");
            return ExitCode::from(2);
        }
    };
    match result {
        Ok(()) => ExitCode::SUCCESS,
        Err(e) => {
            eprintln!("{e}");
            ExitCode::FAILURE
        }
    }
}

fn usage_err(msg: &str) -> Diagnostic {
    Diagnostic::new("gan", Span::default(), format!("{msg}\n\n{USAGE}"))
}

// ---- init ----------------------------------------------------------------

const INIT_MAIN: &str = r#"defmodule Main do
  @moduledoc "Entry point generated by gan init."

  def main() do
    IO.puts("Hello from Gandora!")
    IO.puts("2 + 2 * 2 = #{2 + 2 * 2}")
    IO.puts(":math.sqrt(2.0) = #{:math.sqrt(2.0)}")
  end
end
"#;

const INIT_CONFIG: &str = r#"{
  // Gandora compiler configuration (GEP-0001).
  // Python package metadata and dependencies stay in pyproject.toml.
  "source": ["src"],
  "outDir": "dist",
  "targetPython": "3.12",
}
"#;

const INIT_GITIGNORE: &str = "__pycache__/\n*.py[oc]\ndist/\n.gandora/\n.venv/\n";

fn cmd_init(args: &[String]) -> Result<(), Diagnostic> {
    if args.iter().any(|a| a == "--package") {
        return cmd_init_package(args);
    }
    let existing = args.iter().any(|a| a == "--existing");
    let path: PathBuf = args
        .iter()
        .find(|a| !a.starts_with("--"))
        .map(PathBuf::from)
        .unwrap_or_else(|| PathBuf::from("."));
    if !existing {
        if path.exists() && path != Path::new(".") {
            return Err(Diagnostic::new(
                path.display().to_string(),
                Span::default(),
                "path already exists; use `gan init --existing` to join it",
            ));
        }
        std::fs::create_dir_all(&path).map_err(io_err(&path))?;
    } else if !path.exists() {
        return Err(Diagnostic::new(
            path.display().to_string(),
            Span::default(),
            "--existing requires an existing directory",
        ));
    }
    let name = path
        .canonicalize()
        .ok()
        .and_then(|p| p.file_name().map(|n| n.to_string_lossy().to_string()))
        .unwrap_or_else(|| "gandora-app".to_string());

    write_if_absent(&path.join("gandora.jsonc"), INIT_CONFIG)?;
    write_if_absent(&path.join(".gitignore"), INIT_GITIGNORE)?;
    write_if_absent(&path.join(".python-version"), "3.12\n")?;
    let pyproject = format!(
        "[project]\nname = \"{name}\"\nversion = \"0.1.0\"\ndescription = \"A Gandora project\"\nrequires-python = \">=3.12\"\ndependencies = []\n"
    );
    write_if_absent(&path.join("pyproject.toml"), &pyproject)?;
    std::fs::create_dir_all(path.join("src")).map_err(io_err(&path))?;
    write_if_absent(&path.join("src/main.gan"), INIT_MAIN)?;
    println!("Initialized Gandora project in {}", path.display());
    println!("Next steps:");
    if path != Path::new(".") {
        println!("  cd {}", path.display());
    }
    println!("  gan run src/main.gan");
    Ok(())
}

/// `gan init --package <name>`: a publishable package project (GEP-0006-R001).
fn cmd_init_package(args: &[String]) -> Result<(), Diagnostic> {
    let path: PathBuf = args
        .iter()
        .find(|a| !a.starts_with("--"))
        .map(PathBuf::from)
        .ok_or_else(|| usage_err("init --package requires a package name"))?;
    if path.exists() {
        return Err(Diagnostic::new(
            path.display().to_string(),
            Span::default(),
            "path already exists",
        ));
    }
    let dist_name = path
        .file_name()
        .map(|n| n.to_string_lossy().to_string())
        .unwrap_or_else(|| "gandora-pkg".to_string());
    let py_pkg = dist_name.replace('-', "_");
    let module = project::snake_to_camel(&py_pkg);
    std::fs::create_dir_all(path.join("src").join(&py_pkg)).map_err(io_err(&path))?;

    // outDir must not be `dist`: hatchling excludes its own artifact
    // directory from wheel inputs
    let config = r#"{
  // Gandora package project (GEP-0006): `gan build` also emits the
  // gandora.toml marker and ships .gan sources for macro consumers.
  "source": ["src"],
  "outDir": "pkg",
  "targetPython": "3.12",
  "package": true,
}
"#;
    std::fs::write(path.join("gandora.jsonc"), config).map_err(io_err(&path))?;
    let pyproject = format!(
        r#"[project]
name = "{dist_name}"
version = "0.1.0"
description = "A Gandora package"
requires-python = ">=3.12"
dependencies = []

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

# pkg/ is gitignored build output but must enter the distribution
[tool.hatch.build]
ignore-vcs = true

# the sdist carries sources and the compiled output of `gan build`
[tool.hatch.build.targets.sdist]
include = ["pkg", "src", "gandora.jsonc"]

# the wheel packages the compiled output (marker and .gan sources included)
[tool.hatch.build.targets.wheel]
packages = ["pkg/{py_pkg}"]
"#
    );
    std::fs::write(path.join("pyproject.toml"), pyproject).map_err(io_err(&path))?;
    std::fs::write(
        path.join(".gitignore"),
        format!("{INIT_GITIGNORE}pkg/\n"),
    )
    .map_err(io_err(&path))?;
    std::fs::write(path.join(".python-version"), "3.12\n").map_err(io_err(&path))?;
    let starter = format!(
        r#"defmodule {module}.Core do
  @moduledoc "Public surface of {dist_name}: functions run anywhere, macros expand in consumers."

  def hello(name), do: "Hello from {dist_name}, #{{name}}!"

  defmacro twice(expr) do
    quote do
      {{unquote(expr), unquote(expr)}}
    end
  end
end
"#
    );
    std::fs::write(path.join("src").join(&py_pkg).join("core.gan"), starter)
        .map_err(io_err(&path))?;
    println!("Initialized Gandora package {dist_name} in {}", path.display());
    println!("Publish with:");
    println!("  cd {}", path.display());
    println!("  gan build && uv build && uv publish");
    Ok(())
}

fn write_if_absent(path: &Path, content: &str) -> Result<(), Diagnostic> {
    if path.exists() {
        return Ok(());
    }
    std::fs::write(path, content).map_err(io_err(path))
}

fn io_err(path: &Path) -> impl Fn(std::io::Error) -> Diagnostic + '_ {
    move |e| Diagnostic::new(path.display().to_string(), Span::default(), e.to_string())
}

// ---- project helpers -----------------------------------------------------

fn config_for_cwd() -> Result<project::Config, Diagnostic> {
    let cwd = std::env::current_dir()
        .map_err(|e| Diagnostic::new("gan", Span::default(), e.to_string()))?;
    match project::find_config(&cwd)? {
        Some(c) => Ok(c),
        None => Ok(project::Config::default_at(cwd)),
    }
}

fn config_for_file(file: &Path) -> Result<project::Config, Diagnostic> {
    let dir = file
        .canonicalize()
        .map_err(io_err(file))?
        .parent()
        .map(|p| p.to_path_buf())
        .unwrap_or_default();
    match project::find_config(&dir)? {
        Some(c) => Ok(c),
        None => Ok(project::Config::default_at(dir)),
    }
}

fn sources_or_explicit(
    config: &project::Config,
    files: &[String],
) -> Result<Vec<(PathBuf, Vec<String>)>, Diagnostic> {
    if files.is_empty() {
        let sources = project::discover_sources(config)?;
        project::check_collisions(&sources)?;
        return Ok(sources);
    }
    let mut out = Vec::new();
    for f in files {
        let path = PathBuf::from(f).canonicalize().map_err(io_err(Path::new(f)))?;
        let module = module_for(config, &path)?;
        out.push((path, module));
    }
    Ok(out)
}

fn module_for(config: &project::Config, path: &Path) -> Result<Vec<String>, Diagnostic> {
    for root in &config.source {
        let root_path = config.root.join(root);
        if let Ok(canon_root) = root_path.canonicalize() {
            if path.starts_with(&canon_root) {
                return project::module_name_for(path, &canon_root);
            }
        }
    }
    // outside a source root: derive from the file name only
    project::module_name_for(path, path.parent().unwrap_or(Path::new("")))
}

/// The whole project compiled together with `file` guaranteed included.
fn compile_project_with(
    config: &project::Config,
    file: &Path,
) -> Result<Vec<project::CompiledModule>, Diagnostic> {
    let mut sources = project::discover_sources(config)?;
    let canon = file.canonicalize().map_err(io_err(file))?;
    if !sources.iter().any(|(p, _)| *p == canon) {
        let module = module_for(config, &canon)?;
        sources.push((canon, module));
    }
    project::check_collisions(&sources)?;
    project::compile_files(&sources, Some(&config))
}

// ---- commands ------------------------------------------------------------

fn cmd_check(args: &[String]) -> Result<(), Diagnostic> {
    let config = config_for_cwd()?;
    let sources = sources_or_explicit(&config, args)?;
    if sources.is_empty() {
        println!("no .gan sources found");
        return Ok(());
    }
    let modules = project::compile_files(&sources, Some(&config))?;
    println!("checked {} module(s), no errors", modules.len());
    Ok(())
}

fn cmd_build() -> Result<(), Diagnostic> {
    let config = config_for_cwd()?;
    let modules = project::compile_project(&config)?;
    if modules.is_empty() {
        println!("no .gan sources found");
        return Ok(());
    }
    let out_root = config.root.join(&config.out_dir);
    project::write_outputs(&modules, &out_root)?;
    if config.package {
        let tops = project::write_package_artifacts(&modules, &out_root)?;
        for top in tops {
            println!("packaged {top} (marker + shipped sources)");
        }
    }
    let macro_only = modules.iter().filter(|m| m.compile_time_only).count();
    if macro_only > 0 {
        println!(
            "compiled {} module(s) into {} ({macro_only} macro-only, no runtime output)",
            modules.len() - macro_only,
            out_root.display()
        );
    } else {
        println!(
            "compiled {} module(s) into {}",
            modules.len(),
            out_root.display()
        );
    }
    Ok(())
}

fn cmd_compile(args: &[String]) -> Result<(), Diagnostic> {
    let mut files = Vec::new();
    let mut out_dir: Option<String> = None;
    let mut it = args.iter();
    while let Some(a) = it.next() {
        if a == "--out" {
            out_dir = it.next().cloned();
            if out_dir.is_none() {
                return Err(usage_err("--out requires a directory"));
            }
        } else {
            files.push(a.clone());
        }
    }
    if files.is_empty() {
        return Err(usage_err("compile requires at least one file"));
    }
    let config = config_for_file(Path::new(&files[0]))?;
    let sources = sources_or_explicit(&config, &files)?;
    let modules = project::compile_files(&sources, Some(&config))?;
    let out_root = match out_dir {
        Some(d) => PathBuf::from(d),
        None => config.root.join(&config.out_dir),
    };
    let written = project::write_outputs(&modules, &out_root)?;
    for w in written {
        println!("{}", w.display());
    }
    Ok(())
}

fn cmd_expand(args: &[String]) -> Result<(), Diagnostic> {
    let file = args
        .first()
        .ok_or_else(|| usage_err("expand requires a file"))?;
    let path = Path::new(file);
    let config = config_for_file(path)?;
    let canon = path.canonicalize().map_err(io_err(path))?;
    // macros from the whole project are visible, as during compilation
    let mut sources = project::discover_sources(&config)?;
    if !sources.iter().any(|(p, _)| *p == canon) {
        let module = module_for(&config, &canon)?;
        sources.push((canon.clone(), module));
    }
    let mut table = expander::MacroTable::new();
    let mut target = None;
    for (source, _) in &sources {
        let name = source.display().to_string();
        let text = std::fs::read_to_string(source).map_err(io_err(source))?;
        let term = parser::parse_file(&name, &text)?;
        for (k, v) in expander::collect_macros(&name, &term)? {
            table.entry(k).or_insert(v);
        }
        if *source == canon {
            target = Some(term);
        }
    }
    let term = target.ok_or_else(|| usage_err("expand requires a file"))?;
    let mut ex = expander::Expander::new(file, table);
    let expanded = ex.expand_module(&term)?;
    print!("{}", printer::print_module(&expanded));
    Ok(())
}

fn cmd_run(args: &[String]) -> ExitCode {
    let Some(file) = args.first() else {
        eprintln!("{}", usage_err("run requires a file"));
        return ExitCode::from(2);
    };
    let file_path = PathBuf::from(file);
    let config = match config_for_file(&file_path) {
        Ok(c) => c,
        Err(e) => {
            eprintln!("{e}");
            return ExitCode::FAILURE;
        }
    };
    let modules = match compile_project_with(&config, &file_path) {
        Ok(m) => m,
        Err(e) => {
            eprintln!("{e}");
            return ExitCode::FAILURE;
        }
    };
    let cache_root = config.root.join(".gandora/cache");
    if let Err(e) = project::write_outputs(&modules, &cache_root) {
        eprintln!("{e}");
        return ExitCode::FAILURE;
    }
    let canon = match file_path.canonicalize() {
        Ok(c) => c,
        Err(e) => {
            eprintln!("gan: {e}");
            return ExitCode::FAILURE;
        }
    };
    let Some(target) = modules.iter().find(|m| m.source == canon) else {
        eprintln!("gan: internal error: target module missing from build");
        return ExitCode::FAILURE;
    };
    if target.compile_time_only {
        eprintln!(
            "gan: {} defines only macros; there is nothing to run (GEP-0002-R009)",
            target.module.join(".")
        );
        return ExitCode::FAILURE;
    }
    let script = cache_root.join(&target.py_path);
    let (program, mut pre_args) = project::interpreter_command(&config.root);
    // -P (PYTHONSAFEPATH) keeps the script's own directory off sys.path, so
    // a generated module like tour/numpy.py cannot shadow the real numpy
    // for its siblings; project modules resolve through PYTHONPATH instead.
    pre_args.push("-P".to_string());
    pre_args.push(script.display().to_string());
    pre_args.extend(args[1..].iter().cloned());
    let mut command = std::process::Command::new(&program);
    command.args(&pre_args);
    let existing = std::env::var("PYTHONPATH").unwrap_or_default();
    let pythonpath = if existing.is_empty() {
        cache_root.display().to_string()
    } else {
        format!("{}:{existing}", cache_root.display())
    };
    command.env("PYTHONPATH", pythonpath);
    match command.status() {
        Ok(status) => match status.code() {
            Some(code) => ExitCode::from(code.clamp(0, 255) as u8),
            None => ExitCode::FAILURE,
        },
        Err(e) => {
            eprintln!("gan: failed to launch {program}: {e}");
            ExitCode::FAILURE
        }
    }
}

// ---- documentation (GEP-0007) --------------------------------------------

/// RFC 4647-style lookup over doc entries (GEP-0007-R004).
fn lookup_locale<'a>(info: &'a codegen::DocInfo, locale: Option<&str>) -> Option<&'a str> {
    if let Some(tag) = locale {
        let want = tag.to_lowercase();
        // exact, then an entry the request is a prefix of, then shorten
        if let Some((_, text)) = info
            .entries
            .iter()
            .find(|(t, _)| t.to_lowercase() == want)
        {
            return Some(text);
        }
        if let Some((_, text)) = info
            .entries
            .iter()
            .find(|(t, _)| t.to_lowercase().starts_with(&format!("{want}-")))
        {
            return Some(text);
        }
        if let Some((head, _)) = want.rsplit_once('-') {
            return lookup_locale(info, Some(head));
        }
    }
    info.default_text()
}

fn cmd_doc(args: &[String]) -> Result<(), Diagnostic> {
    let mut target: Option<String> = None;
    let mut locale: Option<String> = None;
    let mut it = args.iter();
    while let Some(a) = it.next() {
        if a == "--locale" {
            locale = it.next().cloned();
            if locale.is_none() {
                return Err(usage_err("--locale requires a BCP 47 tag"));
            }
        } else {
            target = Some(a.clone());
        }
    }
    let Some(target) = target else {
        return Err(usage_err("doc requires a Module or Module.function target"));
    };
    // `App.Mod.fun` -> module App.Mod + function fun; `App.Mod` -> module doc
    let segs: Vec<&str> = target.split('.').collect();
    let (module_name, fun) = match segs.last() {
        Some(last) if last.chars().next().is_some_and(|c| c.is_lowercase()) => {
            (segs[..segs.len() - 1].join("."), Some((*last).to_string()))
        }
        _ => (target.clone(), None),
    };
    if module_name.is_empty() {
        return Err(usage_err("doc target must include a module name"));
    }
    let config = config_for_cwd()?;
    // locate the module source: project first, then installed packages
    let mut source: Option<PathBuf> = None;
    for (path, module) in project::discover_sources(&config)? {
        if module.join(".") == module_name {
            source = Some(path);
            break;
        }
    }
    if source.is_none() {
        source = project::find_installed_source(&config, &module_name);
    }
    let Some(source) = source else {
        return Err(Diagnostic::new(
            "gan",
            Span::default(),
            format!("module {module_name} not found in project sources or installed packages"),
        ));
    };
    let file = source.display().to_string();
    let text = std::fs::read_to_string(&source).map_err(io_err(&source))?;
    let term = parser::parse_file(&file, &text)?;

    let mut module_doc: Option<codegen::DocInfo> = None;
    let mut fun_doc: Option<codegen::DocInfo> = None;
    let mut pending: Option<codegen::DocInfo> = None;
    for stmt in term.as_block() {
        if !stmt.is_call_named("defmodule") {
            continue;
        }
        let ast::Term::Call(dm) = &stmt else { continue };
        let Some(body) = ast::Term::keyword_arg(&dm.args, "do") else { continue };
        for inner in body.as_block() {
            let ast::Term::Call(c) = &inner else { continue };
            let ast::Callee::Name(name) = &c.callee else { continue };
            match name.as_str() {
                "@moduledoc" => module_doc = Some(codegen::doc_info_from_args(&file, c)?),
                "@doc" => pending = Some(codegen::doc_info_from_args(&file, c)?),
                "@doc_trans" => {
                    if let Some(info) = pending.as_mut() {
                        codegen::merge_doc_trans(&file, c, info, "@doc_trans")?;
                    }
                }
                "@example" => {
                    let ex = codegen::example_from_args(&file, c)?;
                    pending
                        .get_or_insert_with(codegen::DocInfo::default)
                        .examples
                        .push(ex);
                }
                "@moduledoc_trans" => {
                    if let Some(info) = module_doc.as_mut() {
                        codegen::merge_doc_trans(&file, c, info, "@moduledoc_trans")?;
                    }
                }
                "def" | "defp" | "defmacro" => {
                    let head_name = c.args.first().and_then(|h| match h {
                        ast::Term::Call(hc) => match &hc.callee {
                            ast::Callee::Name(n) => Some(n.clone()),
                            _ => None,
                        },
                        ast::Term::Var(n, _) => Some(n.clone()),
                        _ => None,
                    });
                    if let (Some(f), Some(h)) = (&fun, &head_name) {
                        if f == h && fun_doc.is_none() {
                            fun_doc = pending.take();
                        }
                    }
                    pending = None;
                }
                _ => {}
            }
        }
    }
    let (label, info) = match &fun {
        Some(f) => (format!("{module_name}.{f}"), fun_doc),
        None => (module_name.clone(), module_doc),
    };
    match info {
        Some(info) if info.hidden => println!("{label} is hidden (@doc false)"),
        Some(info) => {
            let prose = lookup_locale(&info, locale.as_deref());
            if prose.is_none() && info.examples.is_empty() {
                println!("{label} has no documentation");
            } else {
                if let Some(text) = prose {
                    print!("{}", ensure_trailing_newline(text));
                }
                // shared @example blocks are shown in every locale
                for ex in &info.examples {
                    println!();
                    print!("{}", ensure_trailing_newline(ex.trim_end()));
                }
            }
        }
        None => println!("{label} has no documentation"),
    }
    Ok(())
}

fn ensure_trailing_newline(s: &str) -> String {
    if s.ends_with('\n') {
        s.to_string()
    } else {
        format!("{s}\n")
    }
}

/// Run every generated module through Python's doctest runner (GEP-0007-R008).
fn cmd_test() -> ExitCode {
    let config = match config_for_cwd() {
        Ok(c) => c,
        Err(e) => {
            eprintln!("{e}");
            return ExitCode::FAILURE;
        }
    };
    let modules = match project::compile_project(&config) {
        Ok(m) => m,
        Err(e) => {
            eprintln!("{e}");
            return ExitCode::FAILURE;
        }
    };
    let cache_root = config.root.join(".gandora/cache");
    if let Err(e) = project::write_outputs(&modules, &cache_root) {
        eprintln!("{e}");
        return ExitCode::FAILURE;
    }
    let (program, base_args) = project::interpreter_command(&config.root);
    let mut checked = 0usize;
    let mut failed = 0usize;
    // import by dotted module name (not file path): `python -m doctest file`
    // inserts the file's own directory into sys.path, which lets a module
    // like tour/numpy.py shadow the real numpy for its siblings
    const RUNNER: &str = "import sys, doctest, importlib\n\
                          mod = importlib.import_module(sys.argv[1])\n\
                          sys.exit(1 if doctest.testmod(mod).failed else 0)";
    for m in modules.iter().filter(|m| !m.compile_time_only) {
        let dotted = m.py_path.trim_end_matches(".py").replace('/', ".");
        let mut command = std::process::Command::new(&program);
        command.args(&base_args);
        command.args(["-P", "-c", RUNNER, &dotted]);
        command.env("PYTHONPATH", &cache_root);
        checked += 1;
        match command.status() {
            Ok(status) if status.success() => {}
            Ok(_) => {
                eprintln!("doctest failures in {}", m.module.join("."));
                failed += 1;
            }
            Err(e) => {
                eprintln!("gan: failed to launch {program}: {e}");
                return ExitCode::FAILURE;
            }
        }
    }
    println!("doctests: {checked} module(s) checked, {failed} failed");
    if failed == 0 {
        ExitCode::SUCCESS
    } else {
        ExitCode::FAILURE
    }
}
