# Type stub for the gandora_core native extension (GEP-0025-R008:
# artifact verification and editors resolve the API through this file).
from typing import Any

class CompileError(Exception): ...

def version() -> str: ...
def parse(source: str, path: str = "nofile") -> Any: ...
def expand(source: str, path: str = "nofile", root: str | None = None) -> Any: ...
def compile_string(source: str, path: str = "nofile", root: str | None = None) -> str: ...
def diagnostics(source: str, path: str = "nofile", root: str | None = None) -> list[dict[str, Any]]: ...
def tokens(source: str, path: str = "nofile") -> list[Any]: ...
def doc(target: str, root: str | None = None) -> dict[str, Any] | None: ...
def definition(target: str, root: str | None = None) -> dict[str, Any] | None: ...
def symbols(module: str, root: str | None = None) -> list[dict[str, Any]]: ...
def references(target: str, root: str | None = None) -> list[dict[str, Any]]: ...
def wsymbols(query: str, root: str | None = None) -> list[dict[str, Any]]: ...
def local_pref(root: str, key: str) -> str | None: ...
def compile_snippet(source: str, root: str | None = None) -> str: ...
def resolve(root: str, module_name: str) -> dict[str, Any]: ...
def build(root: str, out: str | None = None) -> list[dict[str, Any]]: ...
def check(root: str) -> list[dict[str, Any]]: ...
